# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-09 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessboard',
            name='player',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='chessboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chess_app.Chessboard'),
        ),
    ]
