# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-07-20 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0002_auto_20200609_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessboard',
            name='current_player_type',
            field=models.CharField(blank=True, default='player', max_length=10, null=True),
        ),
    ]
